### ISSUE TITLE
Git credential manager keeps poping up

### ISSUE THREAD

**Issue by twenzel** [awaescher/RepoZ#101]
I'm using your lovely tool a long time.
But since I started using it the GIT Credential Manager for windows keeps poping up asking for credentials. When I'm not enter the credentials or closing the window a new popup will raise after a certain amount of time. And again and again.
![processes](https://user-images.githubusercontent.com/500376/74006352-b550d500-497b-11ea-893a-ffede4caa1ed.jpg)
I don't know if this is an issue on git's side or with repoz. I don't know if git returns any status code back so you can suppress refreshing the git status for a while.

repoz is checking 48 repositories, auto refresh is set to discrete.

**Comment by awaescher** [comment]
No repro .. :(
