### ISSUE TITLE
Crash when scanning computer

### ISSUE THREAD

**Issue by mohas** [awaescher/RepoZ#104]
Hi, the app crashes after a while when I click on scan computer, I could not find any logs to include here but found these in event viewer:

Faulting application name: RepoZ.exe, version: 5.3.0.0, time stamp: 0x5e9df994
Faulting module name: ntdll.dll, version: 10.0.18362.778, time stamp: 0x3dcfaabb
Exception code: 0xc0000374
Fault offset: 0x000dfa1d
Faulting process id: 0x3624
Faulting application start time: 0x01d6278ddd791d82
Faulting application path: C:\Program Files\RepoZ\RepoZ.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 7b841bfc-315c-4ba3-803f-3e9f4690b697
Faulting package full name: 
Faulting package-relative application ID: 

================AND===============

Fault bucket 1784766718693828737, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: RepoZ.exe
P2: 5.3.0.0
P3: 5e9df994
P4: StackHash_8ddd
P5: 10.0.18362.778
P6: 3dcfaabb
P7: c0000374
P8: PCH_A6_FROM_ntdll+0x000723CC
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4D6F.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER506E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER509D.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER50AB.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER50DB.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_RepoZ.exe_9d54104b3b64ae7277e8f41ea862f6f58d823ae0_8a994293_ff832f67-36af-4dd8-a263-c279894cc56e

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7b841bfc-315c-4ba3-803f-3e9f4690b697
Report Status: 268435456
Hashed bucket: 8f58bb7a65700b8488c4c3dfe2af6881
Cab Guid: 0

**Comment by awaescher** [comment]
I'm sorry mohas, but due to the lack of further information, I cannot do anything here.
I suspect an execution prevention in your case like an anti virus app. You could check if you find logs or quarantine info for RepoZ.exe and if you're feeling brave: Try to turn off your anti virus temporarily and re-run your test - not to solve the problem but to find out whether or not this is the case.

**Comment by mohas** [comment]
This is a real issue please don't close it yet. I don't think that I have an antivirus I've debugged it from source and debugger crashed so maybe an insufficient memory problem?

**Comment by awaescher** [comment]
> " ... so maybe an insufficient memory problem?"

What should I do about that?

**Comment by mohas** [comment]
I will work on it after doing my passed due projects :) I want to help with
some other features too

**Comment by awaescher** [comment]
Sounds great, thank you. Please feel free to reopen the issue once you can get your hands on.
