### ISSUE TITLE
Is there a way to configure Ctrl+Enter keys to open up Git-Bash instead of PS in Windows?

### ISSUE THREAD

**Issue by Davis8988** [awaescher/RepoZ#105]
I would love to have a way to configure what happens what I open up the search menu [Ctrl+ALT+R] and then selecting a project and then pressing Ctrl+Enter.
You program is awsome by the way

**Comment by awaescher** [comment]
Thanks Davis. Currently, this is not possible. I'd consider to add this.

**Comment by awaescher** [comment]
I will track this with issue #108
