### ISSUE TITLE
Open in VS Code

### ISSUE THREAD

**Issue by jongio** [awaescher/RepoZ#108]
It would be cool if I could open a repo in VS Code...or make that menu configurable so I can add a custom "open in".

**Comment by awaescher** [comment]
Oh my gosh, of course ... VS Code. How could I NOT come up with this?
Thanks. Yes, I'll have to open up the context menu, I think ...

**Comment by jongio** [comment]
:)

One thing. Lots of people use code insiders. Which has al the same commands as code.exe but it is called code-insiders.exe

**Comment by awaescher** [comment]
Good to know, thanks.

Btw, I actually just read this:
- https://techcrunch.com/2020/05/19/the-mystery-of-rgv2cw-microsofts-extremely-nerdy-secret-message-to-developers/

And the last sentence was like:

![image](https://user-images.githubusercontent.com/3630638/86173056-a5e74980-bb1f-11ea-933a-615fcd6916be.png)

You were behind all this?
![image](https://user-images.githubusercontent.com/3630638/86173078-b26ba200-bb1f-11ea-88e4-6b8c1a632ab1.png)

How cool's that? 😄

**Comment by jongio** [comment]
Yeah, very cool :)

**Comment by jongio** [comment]
When you gonna release new version that includes this?

**Comment by awaescher** [comment]
I hope I find some time this week.

**Comment by awaescher** [comment]
[Version 5.4](https://github.com/awaescher/RepoZ/releases/tag/v5.4) was just released 🥳
