### ISSUE TITLE
Support search repository name (from url)

### ISSUE THREAD

**Issue by chucklu** [awaescher/RepoZ#113]
Running the following command to use the worktree feature of Git
1. mkdir [SuperSocket](https://github.com/kerryjiang/SuperSocket)

2. cd SuperSocket

3. git clone url main (get a folder as main with default branch, the folder is under SuperSocket folder)

4. cd main

5. git worktree add -b v1.6 ../v1.6 origin/v1.6 (get a folder as v1.6 with branch v1.6, the folder is under SuperSocket folder)

6. git worktree add -b v1.5 ../v.15 origin/v1.5(get a folder as v1.5 with branch v1.5, the folder is under SuperSocket folder)

7.  git worktree list

Currently when I try to search "SuperSocket" in repository list, I get nothing.  The search feature could be better, to search through the repository name from the url of remote SuperSocket](https://github.com/kerryjiang/SuperSocket.

**Comment by chucklu** [comment]
1.It would be better, if you can show the remote url on repository list.
Currently it's not easy to distinct the repositories when I have multiple repositories share the same branch name.
Since a local repository might have multiple remotes, you can provide the max number of remote url to show. Make it configurable, default to 3.
2.add prefix `branch name:` and `folder name:` would be better when the branch name and the folder name is the same when use git worktree feature.
![image](https://user-images.githubusercontent.com/3004057/88356013-0a04d280-cd99-11ea-9a58-14d169ff6489.png)

**Comment by awaescher** [comment]
Thanks for the suggestion, but I won't add the remotes to the UI since this would add way too much clutter. Having multiple remotes uris would make that awful and adding a configuration for max. remotes is exactly what a good UI should not have.

The branch name and the folder name are the same in that given scenario. I never had this issue by myself and I think this is an edge case. I'd encourage you to fork this repo and add this feature for yourself. 

Keeping this issue open because I'll think about adding the remotes as filter targets like the current branch or local path.

![image](https://user-images.githubusercontent.com/3630638/88378475-5c49f180-cda1-11ea-8b8c-0f97ceee984a.png)

**Comment by awaescher** [comment]
After some consideration, I decided to not implement this.

**Comment by patriksvensson** [comment]
One feature that would be nice to have (somewhat related to this) is showing the file path if there are multiple repositories with the same name.

So if I have two repositories in the RepoZ list called Foo (one upstream and one fork), it would show the file path under the repository name. Right now I have to hover the repository with the mouse to make sure I choose the right one.

**Comment by awaescher** [comment]
I usually clone these repos in speaking folder names by adding a local name at the end of the clone command, like `git clone https://github.com/awaescher/guics awaescher-guics` (or renaming the repository folder afterwards, which is supported by RepoZ, too).

**Comment by patriksvensson** [comment]
I don't do that. I keep them separated in folders like github/owner/repo. Displaying folder path in case of two identical repos wouldn't change anything for people following a similar pattern as you.

**Comment by chucklu** [comment]
@patriksvensson For your situation, one upstream and one fork, I always make them in same local repository by add another remote.
`git remote add RemoteName url`
then `git fetch --all`
