### ISSUE TITLE
Font colors are quite dark with macOS dark mode

### ISSUE THREAD

**Issue by Cheesebaron** [awaescher/RepoZ#115]
![Screenshot 2020-07-29 at 08 16 24](https://user-images.githubusercontent.com/249719/88763679-d13b7380-d173-11ea-8f6f-750c7b03ae33.png)

For me it is hard to read the light gray on top of the other gray nuance. I think it would be a good idea to tweak these colors a bit for better readability.

**Comment by awaescher** [comment]
I hope you agree that this looks better now:

![BigSur](https://user-images.githubusercontent.com/3630638/102831327-ccf64800-43eb-11eb-8676-e5a6e698c943.png)

**Comment by Cheesebaron** [comment]
Yep, looks much better now. Thank you!

**Comment by awaescher** [comment]
Hey @Cheesebaron, RepoZ 5.5 was just released bringing the updated UI on macOS --> [Tweet](https://twitter.com/Waescher/status/1345521063418093568)

Would you mind helping RepoZ get a little more visibility if you're still happy with it? 😇

**Comment by Cheesebaron** [comment]
@awaescher yep. I've retweeted. Good stuff!

**Comment by awaescher** [comment]
I've seen it, thank you 😊
