### ISSUE TITLE
Manually adding repos

### ISSUE THREAD

**Issue by cristiulian** [awaescher/RepoZ#122]
I really like this tool, it's just what I needed.
Except for the fact that I can't manually add repositories, instead of scanning the all computer.
I have so many repositories I don't care about on my machine, it would be nice to just add the few ones I'm working on.
Is there any workaround on this? I know it should automatically detect any change in a file from a repo and add it, but it's not working on my machine (Win 10).

**Comment by awaescher** [comment]
RepoZ should detect changes automatically. It's enough to change a file or switch a branch in git. This even works if you "switch" to a branch you even are already. So `git switch master` should be enough, even if you're on master already.

**Comment by cristiulian** [comment]
Changing a file won't work. However, "git switch master" works.
Thank you!

**Comment by awaescher** [comment]
Okay, that's strange. Then I suppose RepoZ is not able to update the repo's state on file changes, is it?
What happens if you change a file in a repo. Is the status updated? This should be the same mechanism. Maybe your machine does not allow listening for file system changes.
