### ISSUE TITLE
Repos not found in other partition - Mac

### ISSUE THREAD

**Issue by simyco** [awaescher/RepoZ#123]
Hello, great work!
I have an issue on my side, all projects are stored in another partition on my Mac, but when I try to fetch automatically the repos, they are not found
![Screenshot 2020-09-25 at 09 32 15](https://user-images.githubusercontent.com/13273671/94239384-0107bd00-ff12-11ea-8e8f-d563b9beabeb.png)

**Comment by awaescher** [comment]
Hi, really sorry for the late reply.
Can you check whether [this code](https://github.com/awaescher/RepoZ/blob/7100b58c947d169a689d8bb74af3eeae4c1b12f5/RepoZ.Api.Common/IO/DefaultDriveEnumerator.cs#L11) is the problem? I think checking for logical drives could ignore your partition.

**Comment by awaescher** [comment]
I think, that "drives" are not what we want on macOS.

<img width="800" alt="Bildschirmfoto 2020-12-21 um 21 16 35" src="https://user-images.githubusercontent.com/3630638/102818401-d2df2f80-43d1-11eb-8a0b-abff18a051f6.png">

In lack of response, I'll close this. Feel free to reopen.
