### ISSUE TITLE
Open in Visual Studio Code not work

### ISSUE THREAD

**Issue by ridvanaltun** [awaescher/RepoZ#124]
Hi,

I am using Windows 10 version 2004 build 19041.508. 

When i try to open a project using `Open in Visual Studio Code` via repoZ, VS Code opens the project like below in picture: 

![Screenshot 2020-10-02 222414](https://user-images.githubusercontent.com/10441216/94961785-06f73280-04fe-11eb-8ceb-5b227cc33a7e.png)

**Note:** node-restful-api the name of project i tried to open in repoZ, other projects acted like same.  By the way I have no problem with Windows File Explorer, `Open in Windows File Explorer` works fine.

**Comment by ridvanaltun** [comment]
I found the problem cause. My all repos located at `C:\Users\ridva\Google Drive\repositories` folder. VS Code can't open folder when if the folder's path include white space character.

**Solution:** https://stackoverflow.com/a/31830294/7376041

**Comment by awaescher** [comment]
Thanks for your pull request, very welcome

**Comment by awaescher** [comment]
RepoZ 5.5 was just released which fixes this bug.
