### ISSUE TITLE
When right click for a deleted project RepoZ silently crash on Windows

### ISSUE THREAD

**Issue by ridvanaltun** [awaescher/RepoZ#126]
I was tried to ignore a deleted project but RepoZ crashed when i right click the project. I tested left click, works fine.

**Comment by awaescher** [comment]
Sorry, I forgot the reference: I fixed this with #118, thanks for the report.
However, there's no released version, yet.

**Comment by awaescher** [comment]
RepoZ 5.5 was just released which fixes this bug.
