### ISSUE TITLE
Ability for change default behavior for click on repository

### ISSUE THREAD

**Issue by PadreSVK** [awaescher/RepoZ#127]
Hi, it is possible to set default behavior for primary double click on repository?

**Comment by awaescher** [comment]
Hi Patrik.

Sorry, but no, currently this is hard-coded for [Windows](https://github.com/awaescher/RepoZ/blob/7100b58c947d169a689d8bb74af3eeae4c1b12f5/RepoZ.Api.Win/Git/WindowsRepositoryActionProvider.cs#L59)  and [macOS](https://github.com/awaescher/RepoZ/blob/7100b58c947d169a689d8bb74af3eeae4c1b12f5/RepoZ.Api.Mac/IO/MacRepositoryActionProvider.cs#L53).

However, there was a discussion over here in #114. I'd love to hear what you think.

**Comment by awaescher** [comment]
I'd close this issue in favor for #114. Please feel free to re-open if you think this is not related.
