### ISSUE TITLE
Add context menu to open a repository with an external tool (such as GitExtensions)

### ISSUE THREAD

**Issue by SeanFeldman** [awaescher/RepoZ#132]
Currently, RepoZ allows opening external tools (VS Code, Windows Terminal, File Explorer) with the location of the selected repository. It would be nice if there was an option to open a custom tool. In my case, I'm using GitExtentions extensively and would love to be able to configure that as an application I could open from RepoZ context menu.

**Comment by awaescher** [comment]
Hey Sean,

you are not alone. Patrik, Glenn & me were discussing this a few months ago in issue #114.

This is coming, I'm pretty sure. Please give me some time, I did not find a slot to work on this.

**Comment by awaescher** [comment]
Let me close this in favor for issue #114.

Feel free to reopen if this is not what you expected.

**Comment by SeanFeldman** [comment]
@awaescher, yes, exactly that. The title of that issue doesn't do justice to the thread 🙂 
Thank you for pointing to #114 and will up-vote it.

**Comment by awaescher** [comment]
Thanks for the hint, I updated the title.
