### ISSUE TITLE
grr cd not working

### ISSUE THREAD

**Issue by seanmars** [awaescher/RepoZ#139]
When I use `grr cd Repo` it always get the error below

```bash
V: The term 'V' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by awaescher** [comment]
It seems your Terminal does not support Ctrl+V via SendKeys (to paste the cd-command including the repository path). Which one do you use?

**Comment by seanmars** [comment]
> It seems your Terminal does not support Ctrl+V via SendKeys (to paste the cd-command including the repository path). Which one do you use?

I'm using the [Windows Terminal](https://www.microsoft.com/zh-tw/p/windows-terminal/9n0dx20hk701)

**Comment by awaescher** [comment]
Oh, I see this happens when using CMD in Windows Terminal. However it works with PowerShell within Windows Terminal.
Using CMD.exe directly works, too.

I don't know ... this seems to have a low prio to me.

**Comment by seanmars** [comment]
> Oh, I see this happens when using CMD in Windows Terminal. However it works with PowerShell within Windows Terminal.
> Using CMD.exe directly works, too.
> 
> I don't know ... this seems to have a low prio to me.

I'm using PowerShell Core  7.1.0 and I'm sure it can use `ctrl+v` to paste via my keyboard.

**Comment by seanmars** [comment]
Finally I found the problem. I'm using the [PowerToys](https://github.com/microsoft/PowerToys)'s key mapping. It's will affects the effect. I disabled the key mapping and `grr cd` work fine now!

**Comment by awaescher** [comment]
Wow, I did not think that this might be an issue. Thanks for posting.
