### ISSUE TITLE
Triggering context menu on repo item crashes RepoZ

### ISSUE THREAD

**Issue by Depechie** [awaescher/RepoZ#143]
When I want to ignore a repository, I need to open the context menu of the given repository.
Doing this sometimes results in RepoZ crashing.

OS: Mac OS Big Sur 11.1

**Comment by awaescher** [comment]
Thanks for the report. You say "sometimes" like ... it also works sometimes with the same repositores?
Would you think this could be related with #126?

**Comment by Depechie** [comment]
Actually it's simpler... just right clicking on the repo's in my list will often crash the app, so just going from top to bottom.

**Comment by awaescher** [comment]
I'm sorry, I cannot reproduce this on my machines (1x PC, 2x Mac).
Could you clone this repository and run RepoZ in the debugger for me?

**Comment by awaescher** [comment]
Closed due to inactivity
