### ISSUE TITLE
Performance issue searching large set of repositories

### ISSUE THREAD

**Issue by lennoncork** [awaescher/RepoZ#151]
I have a large set of repositories included from a scan. Typing in the search bar often results in a UI freezeup presumably because search occurs on each keypress and there is a lot to get through. I was able to capture a dotTrace of the lockup but it's not super useful. Suggest buffering the keypress a little and adding the ability to cancel the current keypress action if a new one comes while it's executing. 

Happy to take a look at producing a PR for this. 

![image](https://user-images.githubusercontent.com/7624296/123995977-b70da500-d983-11eb-8b48-5627620b93a6.png)

**Comment by awaescher** [comment]
This has to be a massive repository list indeed.
Buffering/Cancelling sounds good to me, happy to review pull requests.
