### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by awaescher** [awaescher/RepoZ#23]
When running a few days, RepoZ shows that it leaks memory by holding a huge amount of the following objects:

- Microsoft.CSharp.RuntimeBinder.Semantics.SYMTBL+Key
- Microsoft.CSharp.RuntimeBinder.Semantics.LocalVariableSymbol
- Microsoft.CSharp.RuntimeBinder.Semantics.CONSTVAL
- Microsoft.CSharp.RuntimeBinder.Semantics.EXPRCONSTANT
- Microsoft.CSharp.RuntimeBinder.Semantics.EXPRCLASS
- Microsoft.CSharp.RuntimeBinder.Semantics.EXPRTYPEOF
- Microsoft.CSharp.RuntimeBinder.Semantics.EXPRLIST
- Microsoft.CSharp.RuntimeBinder.Semantics.MethWithInst
- Microsoft.CSharp.RuntimeBinder.Semantics.CMemberLookupResults
- Microsoft.CSharp.RuntimeBinder.Semantics.EXPRMEMGRP
- Microsoft.CSharp.RuntimeBinder.Semantics.EXPRCALL
- Microsoft.CSharp.RuntimeBinder.Semantics.EXPRWRAP
- Microsoft.CSharp.RuntimeBinder.Semantics.AggregateDeclaration
- Microsoft.CSharp.RuntimeBinder.Semantics.Scope

![image](https://user-images.githubusercontent.com/3630638/29587113-3537f39c-878d-11e7-8553-1201bf66e591.png)

This seems to be very close to a question on StackOverflow:
https://stackoverflow.com/questions/33080252/memory-overflow-having-an-increasing-number-of-microsoft-csharp-runtimebinder-s/34123315

**Comment by wturi** [comment]
Sorry, after such a long time to see this article, he solved my problem, thank you very much

Finally, I would like to ask, what is the DMP software in the article?

Can you tell me if you can?

Thank you very much

**Comment by wturi** [comment]
Sorry, after such a long time to see this article, he solved my problem, thank you very much

Finally, I would like to ask, what is the DMP software in the article?

Can you tell me if you can?

Thank you very much

**Comment by awaescher** [comment]
Hey @wturi, sure.

This is [ANTS Memory Profiler](https://www.red-gate.com/products/dotnet-development/ants-memory-profiler), It's not free but I can really recommend it anyways.

Not really related but if you look for a .NET performance profiler, I'd recommend the free [Codetrack](https://www.getcodetrack.com).
