### ISSUE TITLE
Consider adding to Scoop

### ISSUE THREAD

**Issue by atifaziz** [awaescher/RepoZ#33]
This is a great tool. It would be even greater if could be added to a [Scoop](http://scoop.sh/) bucket for quick and easy installation. It would also avoid needing to do the following:

> To use `grr` throughout your system like you use `git` ..., you have to add its path to the `PATH` variable. Currently, this has to be done by hand.

**Comment by awaescher** [comment]
Looks interesting - I'll look at this once I got the features in I want it to have. Thanks for the feedback.

**Comment by awaescher** [comment]
Currently, I see no need for this. Thanks for the hint, @atifaziz

**Comment by atifaziz** [comment]
> Currently, I see no need for this

Less pollution of `PATH` but perhaps you don't mind? :wink: I do understand, though, that it's not a _need_ but a _nice to have_. Anyway, keep up the great work.
