### ISSUE TITLE
Automatically fetch every X minutes and/or fetch all button from UI

### ISSUE THREAD

**Issue by ScottRFrost** [awaescher/RepoZ#45]
I've found that RepoZ works great in combination with TortoiseGit, but the one thing I'd like to see is a way to fetch from all repos, either automatically every {configurable} minutes or via a button in the UI.  It would be functionally equivalent of right clicking every repo and selecting "fetch" from the menu.

Would this be doable?

**Comment by awaescher** [comment]
Hi Scott, thanks for the suggestion. I implemented very basic operations like push, pull & fetch to the Windows version (only by now).

Does it help to use operations like fetch with multiselect? This is already implemented, just select your repos and use the context menu.

**Comment by ScottRFrost** [comment]
I'm using the Windows version.  Ctrl+A > Right Click > Fetch works pretty well, but it's not easily discoverable by users.  I didn't even think to try it.

**Comment by awaescher** [comment]
I‘d like to keep it that way to preserve a clean UI

**Comment by awaescher** [comment]
Implemented in [Version 4.0](https://github.com/awaescher/RepoZ/releases/tag/v4.0).
Thanks for the feature suggestion 👍
