### ISSUE TITLE
Provide "outdated" Repository information

### ISSUE THREAD

**Issue by twenzel** [awaescher/RepoZ#52]
Please show a little icon/symbol in the repository overview that the remote branch "newer" than the local branch.
You can implement it by an periodical "fetch" and use these information.
The interval of the fetch should be configurable. 

This feature should be disabled by default.

**Comment by awaescher** [comment]
Available from version 4.0 and up :heart:

![Screenshot](_doc/AutoFetch.png)

**Comment by ScottRFrost** [comment]
Aww, this issue got mentioned on the changelog by my similar (and prior https://github.com/awaescher/RepoZ/issues/45) issue didn't.  Feels bad man.

**Comment by awaescher** [comment]
Oh my gosh @ScottRFrost, you're right. I will definitely catch up on that. Man, how exactly you specified the feature the way I implemented it ... 
> ... the one thing I'd like to see is a way to fetch from all repos, either automatically every {configurable} minutes ...

Thank's for the hint.
