### ISSUE TITLE
Provide Chocolatey Package for easy installation

### ISSUE THREAD

**Issue by papauorg** [awaescher/RepoZ#72]
Congrats to your 100 ⭐ milestone! :+1:

It would be great to have a chocolatey package for installing repoz. This would enable easy installation and updates. 

https://chocolatey.org/docs/create-packages

**Comment by awaescher** [comment]
It has taken a while, but RepoZ was finally approved on chocolatey part 🥳

- https://chocolatey.org/packages/repoz
