### ISSUE TITLE
takes too much memory

### ISSUE THREAD

**Issue by zhoujian365** [awaescher/RepoZ#82]
repoz takes too much memory on mac

![image](https://user-images.githubusercontent.com/35226412/62262620-f061d100-b44b-11e9-9d41-0df84b9aebec.png)

**Comment by awaescher** [comment]
Whoa.
Can you add some details like (approx.) repo count and program execution time?

**Comment by zhoujian365** [comment]
macOS 10.14.6, 30+ repos.


Normally it takes little memory. But if I didn’t shut down macOS and just let it sleep, the next day when I open the computer, it will take lots of memory. Seems to be related to mac’s sleep  wake up.


原始邮件
发件人:Andreas Wäschernotifications@github.com
收件人:awaescher/RepoZRepoZ@noreply.github.com
抄送:Zhou Jianzhoujian365@foxmail.com; Authorauthor@noreply.github.com
发送时间:2019年8月1日(周四) 15:43
主题:Re: [awaescher/RepoZ] takes too much memory (#82)


Whoa.
 Can you add some details like (approx.) repo count and program execution time?

**Comment by awaescher** [comment]
I sent my mac to sleep for 3 days now. Unfortunately, I can't see higher memory consumption in RepoZ. Are you able to reproduce this? If so, would you upload a spindump for me to analyse?

**Comment by awaescher** [comment]
Sorry, I cannot reproduce that behavior.
