### ISSUE TITLE
Glitch on opening from time to time

### ISSUE THREAD

**Issue by ipetrushevskiy** [awaescher/RepoZ#87]
![glitch](https://user-images.githubusercontent.com/25434976/65555041-006dcc80-df34-11e9-858c-e4feb1d8acfb.png)

That`s what I have.
Windows Home 10 1903
Multimonitor Extended
Intel UHD 620 GPU

**Comment by awaescher** [comment]
Sorry to see but I don't have anything to repro this.
Do you have further info? Maybe long standby/hibernate times in between or anything like that?

**Comment by ipetrushevskiy** [comment]
Hello again. No. To repo it I just need to open and close window using hotkey for a few times (usually < 10 is enough). Could it be somehow connected with a resolution? Mine is 1440p on the main monitor. Anyways - look like this is somehow connected with a window transparency. Maybe if I could be able to turn it off - it would be pretty enough for me.

**Comment by awaescher** [comment]
Yeah, that could help. I'm going to add a hidden setting for that. However, I'm not sure whether this may help. It's looks so awkward, it does not seem to be deterministic - and it's not limited to UI elements: see that cut button or that strange shape around the search bar.

**Comment by awaescher** [comment]
Good news, I could manage to reproduce this with the latest Windows updates. And I think I fixed it - it's not that easy to be sure because of its irregular nature.

**Comment by awaescher** [comment]
RepoZ 5.1 is out - you can give it a try 🐱‍🏍
