### ISSUE TITLE
"This app might harm your device"

### ISSUE THREAD

**Issue by Whil-** [awaescher/RepoZ#92]
Just wanted to let you know that Microsoft Defender SmartScreen doesn't like the setup.exe.

I get a message in Microsoft edge beta browser:

> Microsoft Defender SmartScreen reported that this app is not commonly downloaded or is not signed by its publisher.
> 
> Name: RepoZ.5.1.Setup.exe
> Publisher: Unknown

**Comment by awaescher** [comment]
Yeah, I know. There's not much to do about it, except spending money for a code signing certificate:

- see https://github.com/awaescher/RepoZ/issues/59

**Comment by Whil-** [comment]
Ah ok - didn't see the other issue. Maybe because it was closed ;) 

I understand your priority. Hope the reputation path solves the issue! 

Thanks
/G

**Comment by awaescher** [comment]
Nevermind, opening issues should not be considered as being offensive ;)
Thanks for the feedback
